version: "3.7"

networks:
  internal:
    driver: bridge

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  cotacaobb:
    image: felipe/cotacao-bb:1.0.0-SNAPSHOT
    ports:
      - 8080:8080
    links:
      - "db"
    depends_on:
      - "db"
    networks:
      - internal

  db:
    image: postgres:10.5
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user_cotacao
      POSTGRES_PASSWORD: cotacao123
      POSTGRES_DB: cotacao_db
    networks:
      - internal

  prometheus:
    image: prom/prometheus:v2.9.2
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./prometheus_data:/prometheus_data
      - ./config:/config
    command:
      - '--config.file=/config/prometheus.yml'
      - '--storage.tsdb.path=/prometheus_data'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    depends_on:
      - "cotacaobb"
    networks:
      - internal
    restart: always

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - "prometheus"
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./config/config.monitoring
    networks:
      - internal
    restart: always

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    networks:
      - internal